# Site settings
title: Ryan Taylor
email: ryan@ryan-taylor.net
url: https://www.linkedin.com/in/ryantaylor-itsm/
description: "Ryan Taylor has been a technical operations leader for software companies specializing in streaming media, security technology, and finance."
keywords: "Hulu Ops, huluops, Hulu Operations, Transposit, Intuit Operations, SRE, DevOps, separated by commas"
skills: "People. Products. Process. Partnership."
meta_author: Taylor Ryan

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: abb1cf #80B3FF
  primary-rgb: "171,177,207" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Ryan Taylor
  location: Los Angeles
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ryantaylor-itsm/
  - title: twitter
    url: http://twitter.com/ryanmtaylor
  - title: instagram
    url: https://www.instagram.com/ryantaylor16

# Postal address (add as many lines as necessary)
address:
  - line: Los Angeles, CA

# Credits content
credits: 'Built with Jekyll and hosted on Github'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
